apiVersion: 1

datasources:
  - name: Quickwit
    type: yesoreyeram-infinity-datasource
    uid: quickwit-index
    access: proxy
    url: http://quickwit:7280
    isDefault: true
    editable: true
    jsonData:
      root_selector: "$.hits"
      data_links:
        - title: "Open in Quickwit"
          url: "http://localhost:7280/ui/search?index=stackoverflow&q=${__data.fields.body:urlencode}"
      columns:
        - selector: "$.num_hits"
          type: number
          text: "Total Hits"
        - selector: "$.elapsed_time_micros"
          type: number
          text: "Latency (μs)"
